### ISSUE TITLE
no dopisz tam siebie wkoncu

### ISSUE THREAD

**Issue by chickeeen** [ProgramistaZpolski/list-of-things-that-are-evil#2]
^^^^^^^^^^^^

**Comment by chickeeen** [comment]
### H

**Comment by ProgramistaZpolski** [comment]
h

**Comment by chickeeen** [comment]
btw. mam pytanie, jak ustawic w tagu html dir, ze piszemy od prawej strony?

**Comment by chickeeen** [comment]
twoj stary to inwalida btw
duasiydbas8ynsaypdhmusai

**Comment by ProgramistaZpolski** [comment]
> ja potem zrobie swoja wersje chomikboxa, bez jakiegos pzplui, czy PH P

what do you have agains pzplui, also http://portalphp.tk/

**Comment by chickeeen** [comment]
> > ja potem zrobie swoja wersje chomikboxa, bez jakiegos pzplui, czy PH P
> 
> what do you have against pzplui, also http://portalphp.tk/

jest robione przez ciebie i wiele innych rzeczy, sass > css btw.

**Comment by chickeeen** [comment]
~~a moze zrobic chomikboxa we vue~~

**Comment by ProgramistaZpolski** [comment]
What's the point?

**Comment by ProgramistaZpolski** [comment]
what

**Comment by TheVision6212** [comment]
![obraz](https://user-images.githubusercontent.com/71152608/110445317-43871580-80be-11eb-9e39-eb2589f50de1.png)

**Comment by ProgramistaZpolski** [comment]
>  ale to bedzie moja wersja, nic sogreenowi kazac nie bede

what did I require sogreeno to do?

**Comment by TheVision6212** [comment]
xD

**Comment by chickeeen** [comment]
> > ale to bedzie moja wersja, nic sogreenowi kazac nie bede
> 
> what did I require sogreeno to do?

nauczyczysz sie kiedyś czytać?
chce tylko zrobić swoją wersję
nie będe kazał sogreenowi JEJ akurat używać
nikt nic nie mówił o tobie

**Comment by chickeeen** [comment]
tylko chcialem powiedziec ze silverlight, php i flash to ściek, dziękuje za uwagę

**Comment by chickeeen** [comment]
telefony telefony
tele-tele-telefony

**Comment by chickeeen** [comment]
telefony telefony
do kogo z was

**Comment by chickeeen** [comment]
telefony w mojej głowie
bez przerwy trrrrrrrrrrrrrrr

**Comment by chickeeen** [comment]
telefony w mojej głowie
(na na na na na na na na na)

**Comment by chickeeen** [comment]
telefony w mojej głowie
(na na na na na na na na na)

**Comment by chickeeen** [comment]
to tylko ja

**Comment by chickeeen** [comment]
tam gdzie dzwonię nie poznają
mego głosu-głosu-głosu-głosu-głosu

**Comment by ProgramistaZpolski** [comment]
> bo chce to zrobic w html/sass(sass > css)/js

what's the point of using sass?

>, jest robione przez ciebie i wiele innych rzeczy, sass > css btw.

what kinds of other things?

**Comment by chickeeen** [comment]
ten telefon w mojej głowie tylko
brzęczy-brzęczy-brzęczy-brzęczy-brzęczy
aaaaaaaaaaaa

**Comment by chickeeen** [comment]
brzęczy-brzęczy-brzęczy-brzęczy-brzęczy
aaaaaaaaaaaa

**Comment by chickeeen** [comment]
kto wydzwoni, kto wykręci
w końcu numer mój

**Comment by chickeeen** [comment]
kto zadzwoni, kto zadzwoni
tutaj do mnie

**Comment by chickeeen** [comment]
telefony w mojej głowie wciąż

**Comment by chickeeen** [comment]
telefony w mojej głowie wciąż

**Comment by chickeeen** [comment]
telefony...
to tylko jaaaaaaaaa...

**Comment by chickeeen** [comment]
telefony w mojej głowie
bez przerwy trrrrrrrrrrrrrrr

**Comment by chickeeen** [comment]
nikt nie dzwoni, nikt nie dzwoni
to tylko ja tylko ja

**Comment by chickeeen** [comment]
telefony w mojej głowie

**Comment by chickeeen** [comment]
telefony w mojej głowie

**Comment by chickeeen** [comment]
telefony w mojej głowie

**Comment by chickeeen** [comment]
to tylko ja!

**Comment by chickeeen** [comment]
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na...
nanananananananana..
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na naaaaaaaaaaaa...

**Comment by chickeeen** [comment]
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na...
nanananananananana..
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na naaaaaaaaaaaa...

**Comment by chickeeen** [comment]
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na...
nanananananananana..
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na naaaaaaaaaaaa...

**Comment by chickeeen** [comment]
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na...
nanananananananana..
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na naaaaaaaaaaaa...

**Comment by chickeeen** [comment]
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na...
nanananananananana..
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na naaaaaaaaaaaa...

**Comment by chickeeen** [comment]
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na...
nanananananananana..
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na na
nanananananananana
na na na na na na naaaaaaaaaaaa...
