### ISSUE TITLE
afsadf

### ISSUE THREAD

**Issue by chickeeen** [ProgramistaZpolski/list-of-things-that-are-evil#4]
asfdsaf

**Comment by ProgramistaZpolski** [comment]
h

**Comment by chickeeen** [comment]
czemu dyskryminujesz twardogórzan, galaretki i radomskomian(nie wiem jak odmienic)

**Comment by ProgramistaZpolski** [comment]
what

**Comment by TheVision6212** [comment]
no dyskryminujesz nas jako mniejszość poprzez np.:
- Cenzurowanie nas
- Zamykanie naszych issue
- Zabranianie nam śpiewania piosenek jakich chcemy
Precz z cenzurą!
Wolne galaretki, twardogórzanie i radomskowianie

**Comment by chickeeen** [comment]
TWOJA STARA TO INWALIDA DIASGHIOSAD

**Comment by SoGreeno** [comment]
co tu sie odwala

**Comment by ProgramistaZpolski** [comment]
> no dyskryminujesz nas jako mniejszość poprzez np.:
> 
>     * Cenzurowanie nas
> 
>     * Zamykanie naszych issue
> 
>     * Zabranianie nam śpiewania piosenek jakich chcemy
>       Precz z cenzurą!
>       Wolne galaretki, twardogórzanie i radomskowianie

Because the issues that you create are not related to the project itself.

**Comment by chickeeen** [comment]
btw jak zamkne issue, jak sie reopenuje? XD @TheVision6212

**Comment by ProgramistaZpolski** [comment]
> co tu sie odwala

They are spamming my repos for some reason

**Comment by SoGreeno** [comment]
chyba sie nie da

**Comment by chickeeen** [comment]
> > no dyskryminujesz nas jako mniejszość poprzez np.:
> > ```
> > * Cenzurowanie nas
> > 
> > * Zamykanie naszych issue
> > 
> > * Zabranianie nam śpiewania piosenek jakich chcemy
> >   Precz z cenzurą!
> >   Wolne galaretki, twardogórzanie i radomskowianie
> > ```
> 
> Because the issues that you create are not related to the project itself.

a właśnie są związane z projektem, bo projekt tworzysz ty, a my mamy problem z twoją osobą :>

**Comment by chickeeen** [comment]
> spamming

twoja stara

**Comment by ProgramistaZpolski** [comment]
> > > no dyskryminujesz nas jako mniejszość poprzez np.:
> > > ```
> > > * Cenzurowanie nas
> > > 
> > > * Zamykanie naszych issue
> > > 
> > > * Zabranianie nam śpiewania piosenek jakich chcemy
> > >   Precz z cenzurą!
> > >   Wolne galaretki, twardogórzanie i radomskowianie
> > > ```
> > 
> > 
> > Because the issues that you create are not related to the project itself.
> 
> a właśnie są związane z projektem, bo projekt tworzysz ty, a my mamy problem z twoją osobą :>

Ever heard about github discussion instead of opening issues?

**Comment by chickeeen** [comment]
> > > > no dyskryminujesz nas jako mniejszość poprzez np.:
> > > > ```
> > > > * Cenzurowanie nas
> > > > 
> > > > * Zamykanie naszych issue
> > > > 
> > > > * Zabranianie nam śpiewania piosenek jakich chcemy
> > > >   Precz z cenzurą!
> > > >   Wolne galaretki, twardogórzanie i radomskowianie
> > > > ```
> > > 
> > > 
> > > Because the issues that you create are not related to the project itself.
> > 
> > 
> > a właśnie są związane z projektem, bo projekt tworzysz ty, a my mamy problem z twoją osobą :>
> 
> Ever heard about github discussion instead of opening issues?

nie rozumiem co napisales, po polsku kurwa napisz uhjskahdsaid

**Comment by SoGreeno** [comment]
> nie rozumiem co napisales, po polsku kurwa napisz uhjskahdsaid

nie chce ale po co chcesz żeby pisał po polsku skoro rozumiesz angielski

**Comment by ProgramistaZpolski** [comment]
> > > > > no dyskryminujesz nas jako mniejszość poprzez np.:
> > > > > ```
> > > > > * Cenzurowanie nas
> > > > > 
> > > > > * Zamykanie naszych issue
> > > > > 
> > > > > * Zabranianie nam śpiewania piosenek jakich chcemy
> > > > >   Precz z cenzurą!
> > > > >   Wolne galaretki, twardogórzanie i radomskowianie
> > > > > ```
> > > > 
> > > > 
> > > > Because the issues that you create are not related to the project itself.
> > > 
> > > 
> > > a właśnie są związane z projektem, bo projekt tworzysz ty, a my mamy problem z twoją osobą :>
> > 
> > 
> > Ever heard about github discussion instead of opening issues?
> 
> nie rozumiem co napisales, po polsku kurwa napisz uhjskahdsaid

There is a feature called [github discussions](https://github.com/ProgramistaZpolski/pzplUI/discussions)

**Comment by chickeeen** [comment]
> > > > > > no dyskryminujesz nas jako mniejszość poprzez np.:
> > > > > > ```
> > > > > > * Cenzurowanie nas
> > > > > > 
> > > > > > * Zamykanie naszych issue
> > > > > > 
> > > > > > * Zabranianie nam śpiewania piosenek jakich chcemy
> > > > > >   Precz z cenzurą!
> > > > > >   Wolne galaretki, twardogórzanie i radomskowianie
> > > > > > ```
> > > > > 
> > > > > 
> > > > > Because the issues that you create are not related to the project itself.
> > > > 
> > > > 
> > > > a właśnie są związane z projektem, bo projekt tworzysz ty, a my mamy problem z twoją osobą :>
> > > 
> > > 
> > > Ever heard about github discussion instead of opening issues?
> > 
> > 
> > nie rozumiem co napisales, po polsku kurwa napisz uhjskahdsaid
> 
> There is a feature called [github discussions](https://github.com/ProgramistaZpolski/pzplUI/discussions)

there is twoj stary pisz po polsku

**Comment by SoGreeno** [comment]
czy możecie nie quote'tować quote'ty plz

**Comment by ProgramistaZpolski** [comment]
> czy możecie nie quote'tować quote'ty plz

ok

**Comment by chickeeen** [comment]
to ze uwazasz, ze polski zly i niedobry, bo masz powody do tego z dvpy wziete, nie znaczy, ze nie mozesz porozmawiac z polakami po polsku

to tak jakbys do hiszpana zaczal po czesku napierdalac

**Comment by ProgramistaZpolski** [comment]
Also, @SoGreeno if you ever need help with pzplUI just create a new [discussion](https://github.com/ProgramistaZpolski/pzplUI/discussions)

**Comment by SoGreeno** [comment]
![image](https://user-images.githubusercontent.com/59972034/110448633-a6c67700-80c1-11eb-81d4-97bb81cb25fa.png)

wait what why family is bad

**Comment by chickeeen** [comment]
"bo tracą twój czas rodząc cię"

**Comment by SoGreeno** [comment]
> "bo tracą twój czas rodząc cię"

c                                                                  o

**Comment by chickeeen** [comment]
> > btw. @ProgramistaZpolski idziesz na vc o 3 PM :>
> 
> what?

co "co?"?
gówno

**Comment by ProgramistaZpolski** [comment]
Can I close this pointless issue?

**Comment by chickeeen** [comment]
no punkt to twoj dom
a potem strzelamy z AUG'a

**Comment by SoGreeno** [comment]
> no punkt to twoj dom
> a potem strzelamy z AUG'a

czy możecie sie uspokoić dziękuje dowidzenia dobranoc

**Comment by ProgramistaZpolski** [comment]
> > no punkt to twoj dom
> > a potem strzelamy z AUG'a
> 
> czy możecie sie uspokoić dziękuje dowidzenia dobranoc

I'd like for everything to be peaceful, but liskqu is constantly spamming my repos in issues.

**Comment by ProgramistaZpolski** [comment]
> > spamming
> 
> NO TWOJA STARA NIE SPAMMING

![Screenshot_2021-03-09 Build software better, together](https://user-images.githubusercontent.com/37271169/110449718-c7430100-80c2-11eb-8387-e44995b20fa1.png)

**Comment by chickeeen** [comment]
> > > spamming
> > 
> > 
> > NO TWOJA STARA NIE SPAMMING
> 
> ![Screenshot_2021-03-09 Build software better, together](https://user-images.githubusercontent.com/37271169/110449718-c7430100-80c2-11eb-8387-e44995b20fa1.png)

to są tylko pytania, lub stwierdzenia że jesteś zjebem

**Comment by SoGreeno** [comment]
ok już nie ma dramy chyba hura

**Comment by ProgramistaZpolski** [comment]
> ok już nie ma dramy chyba hura

I hope that it will end here.

**Comment by chickeeen** [comment]
> > ok już nie ma dramy chyba hura
> 
> I hope that it will end here.

dopoki sie nie ogarniesz to sie nie skonczy
