### ISSUE TITLE
zastanawia mnie coś

### ISSUE THREAD

**Issue by chickeeen** [ProgramistaZpolski/list-of-things-that-are-evil#5]
W liście dobrych rzeczy, umieszczone jest JavaScript, ale w złych, jest też NodeJS, które obwiniasz za cechy JavaScripta.
Czy JavaScript w takim razie według Ciebie również nie powinien być zły?

**Comment by ProgramistaZpolski** [comment]
I think nodejs is bad because it allows for js to run on the server - thats the reason why i put it here

**Comment by chickeeen** [comment]
właśnie, a żeby powstał nodejs, który obsługuje serwery, musiał powstać javascript, z którego korzysta, więc jeżeli nie byłoby js nie było by nodejs :)

**Comment by chickeeen** [comment]
ale, to wciąż trwało, po co to zamykasz lol
