### ISSUE TITLE
add kukanq as evil

### ISSUE THREAD

**Issue by SoGreeno** [ProgramistaZpolski/list-of-things-that-are-evil#6]
kukanq is a chestnut

**Comment by ProgramistaZpolski** [comment]
Sure, i will do this in a few minutes

**Comment by ProgramistaZpolski** [comment]
Added, anything else to add?

**Comment by SoGreeno** [comment]
no

**Comment by chickeeen** [comment]
why

**Comment by SoGreeno** [comment]
> why

what. there's nothing else to add

**Comment by ProgramistaZpolski** [comment]
> > why
> 
> what. there's nothing else to add

he is asking *why* did you decide to add kukanq
