### ISSUE TITLE
request

### ISSUE THREAD

**Issue by SoGreeno** [ProgramistaZpolski/list-of-things-that-are-evil#8]
Add pankoza2008pl as evil because: he changes any text to "pzpl to kasztan" in any programming language. also pzpl isnt kasztan, he likes vbs/batch, the only thing he does is echo pzpl to kasztan.

~~and add python as good~~

**Comment by ProgramistaZpolski** [comment]
ok wait will add soon

**Comment by ProgramistaZpolski** [comment]
added
